### ISSUE TITLE
no bin/delayed_job on server

### ISSUE THREAD

**Issue by jgrannas** [platanus/capistrano3-delayed-job#6] opened 2015-02-24 15:58 UTC
I am trying to deploy to my staging env, but i am getting this:

```bundler: command not found: bin/delayed_job```

I looked in my shared/bin directory and there is no delayed_job file... Is there a task to create this or what is the proper way to do this on the server

I checked my .gitignore, and its not ignoring /bin...

**Comment by blackjid** [comment] 2015-02-24 16:02
are you using rails? if true what version?

**Comment by jgrannas** [comment] 2015-02-24 16:12
rails 4.2

**Comment by jgrannas** [comment] 2015-02-24 16:17
When I try to generate the delayed_job on server I get:
```
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable
```
Is it safe to do this on my development environment, or will it break things?

**Comment by jgrannas** [comment] 2015-02-24 16:28
I found this issue after searching on some of the text in that message above:
https://github.com/capistrano/bundler/issues/45

So in my deploy.rb i changed
set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
TO THIS
set :linked_dirs, %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
removing the bin reference. 

Seems to allow my deploy to go through now.

**Comment by jgrannas** [comment] 2015-02-24 17:24
Ok... so I have 2 jobs in my staging environment's queue, but it seems like they are not getting run...

rails c on staging:
```Delayed::Job.first```
gives me
```#<Delayed::Backend::ActiveRecord::Job id: 1, priority: 0, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject...", last_error: nil, run_at: "2015-02-24 16:30:37", locked_at: "2015-02-24 16:30:41", failed_at: nil, locked_by: "delayed_job host:hostname pid:24026", queue: nil, created_at: "2015-02-24 16:30:37", updated_at: "2015-02-24 16:30:37"> ```

any ideas?

**Comment by blackjid** [comment] 2015-02-24 18:06
It looks like the job is executing, but taking a long time to finish….
(look at the locked_at attribute)
​

On Tue, Feb 24, 2015 at 2:24 PM, Joel Grannas <notifications@github.com>
wrote:

> Ok... so I have 2 jobs in my staging environment's queue, but it seems
> like they are not getting run...
>
> rails c on staging:
>
> gives me
> ```#<Delayed::Backend::ActiveRecord::Job id: 1, priority: 0, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject...", last_error: nil, run_at: "2015-02-24 16:30:37", locked_at: "2015-02-24 16:30:41", failed_at: nil, locked_by: "delayed_job host:hostname pid:24026", queue: nil, created_at: "2015-02-24 16:30:37", updated_at: "2015-02-24 16:30:37"> ```
>
> any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/platanus/capistrano3-delayed-job/issues/6#issuecomment-75801664>
> .
>



-- 

[image: Platanus] <http://platan.us/>

Juan Ignacio Donoso
Co-fundador | Desarrollador | Diseñador
juan.ignacio@platan.us

Platanus: (+562) 28818025
Pedro Canisio 1441, Vitacura, Santiago, Chile

**Comment by jgrannas** [comment] 2015-02-24 18:09
Ok...
Is **locked_at** generated if there is an error in a method? why no failed_at?

**Comment by jgrannas** [comment] 2015-02-24 18:53
Just looked in my staging.log file and found:

```ERROR -- : 2015-02-24T10:58:51-0600: [Worker(delayed_job host:app_name pid:27556)] Job Model#send_to_crm (id=2) FAILED (0 prior attempts) with Mysql2::Error: Lost connection to MySQL server during query```

So... should that host:____ be my external mysql server IP? right now it's my app name...

Basically i have a model with a method "send_to_crm" which connects to the external database using mysql2 connection. This all works locally in develoment... So i am confused as to what is happening on the staging server.

**Comment by blackjid** [comment] 2015-02-24 22:03
mmm, I don't now, do you think that the problem is in the deployment done by this gem???

what happen if you stop the deamon that was started by this gem and start it manually??

**Comment by blackjid** [comment] 2015-06-02 10:41
@jgrannas did you finally be able to fix this? Is this really an issue or I can close it?

**Comment by blackjid** [comment] 2015-07-27 22:46
please feel free to reopen if it is still an issue..

**Closed by blackjid** 2015-07-27 22:46 UTC
